Update recipe extensions to match Whinlatter's recipes
Fix the error below:
ERROR: No recipes in default available for:
freedom-u-sdk/recipes-core/coreutils/coreutils_9.6.bbappend
freedom-u-sdk/recipes-devtools/elfutils/elfutils_0.192.bbappend
freedom-u-sdk/recipes-devtools/tcltk/tcl_9.0.1.bbappend
freedom-u-sdk/recipes-support/opencv/opencv_4.11.0.bbappend

Except that we no longer need the PACKAGECONFIG change from opencv's
bbappend, since the build issue is fixed upstream, so we can drop it entirely.

Signed-off-by: Joao Marcos Costa <joaomarcos.costa@bootlin.com>